### ISSUE TITLE
Задание 7. Добавить операцию получения данных клиента по идентификатору в Telegram

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-middle-service#10]
**TODO:**

- [x] Обновить контракт Middle Service 
- [x] Написать тесты
- [x] Реализовать бизнес-логику
- [x] Обновить версию приложения
- [x] После апрува PR Проставить тег
