### ISSUE TITLE
Задание 8. Добавить операцию запроса баланса

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-middle-service#12]
**TODO:**

- [ ] Обновить контракт Middle Service 
- [ ] Написать тесты
- [ ] Реализовать бизнес-логику
- [ ] Обновить версию приложения
- [ ] После апрува PR Проставить тег

**Comment by saneci** [comment]
Не актуально. Баланс на клиенте получаем в `GET /v1/clients/{telegramId}`.
