### ISSUE TITLE
Задание 9. Добавить операцию перевода со счёта клиента на счёт другого клиента

### ISSUE THREAD

**Issue by saneci** [gpb-it-factory/gladskoy-middle-service#13]
**TODO:**

- [x] Обновить контракт Middle Service 
- [x] Написать тесты
- [x] Реализовать бизнес-логику
- [x] Обновить версию приложения
- [x] После апрува PR Проставить тег
